### ISSUE TITLE
[Charli] Uncaught (in promise) TypeError: Cannot add property contractContext, object is not extensible

### ISSUE THREAD

**Issue by zach-is-my-name** [LIT-Protocol/Issues-and-Reports#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

6.0.3 / 6.0.2

### Lit Network

Cayenne

### Description of the bug/issue

Throws error when calling connect.  I follow the sdk development. I know stuff got changed recently with contractContext

```
Error @  await litNodeClient.connect();
lit-core.js:617 Uncaught (in promise) TypeError: Cannot assign to read only property '_connectingPromise' of object '#<LitNodeClient>'
    at LitNodeClient.connect (lit-core.js:617:33)
    at async eval (useLitSession.tsx:20:7)
    
lit-core.js:630 Uncaught (in promise) 
TypeError: Cannot add property contractContext, object is not extensible
    at LitNodeClient._connect (lit-core.js:630:41)
```

### Severity of the bug

High.  Can't call connect()

### Steps To Reproduce

```
// litClients.ts
import { LitNodeClient } from '@lit-protocol/lit-node-client';
import { LitAuthClient } from '@lit-protocol/lit-auth-client';
import { LIT_NETWORKS_KEYS } from '@lit-protocol/types';

const litNetwork = process.env.NEXT_PUBLIC_LIT_NETWORK_C as LIT_NETWORKS_KEYS;
if (!litNetwork) throw new Error('problem importing litNetwork env')

export const litNodeClient: LitNodeClient = new LitNodeClient({
  alertWhenUnauthorized: false,
  litNetwork,
  checkNodeAttestation: false,
  debug: false
});

export const litAuthClient: LitAuthClient = new LitAuthClient({
   debug: false,
  litRelayConfig: {
    relayApiKey: process.env.NEXT_PUBLIC_LIT_RELAY_API_KEY,
  },
  litNodeClient,
});

// atoms.ts
import { atom, selector } from 'recoil';
import { IRelayPKP, SessionSigs } from '@lit-protocol/types';
import { PKPEthersWallet } from '@lit-protocol/pkp-ethers';
import { LitNodeClient } from '@lit-protocol/lit-node-client';
import {litNodeClient} from '../utils/litClients'
import { SupabaseClient, createClient } from '@supabase/supabase-js';
import { isJwtExpired } from '../utils/app';
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLIC_API_KEY!;

export const litNodeClientAtom = atom<LitNodeClient>({
  key: 'litNodeClient',
  default: litNodeClient,
});
//useLitSession.tsx
import { useCallback, useState } from 'react';
import { AuthMethod, SessionSigs } from '@lit-protocol/types';
import { getProviderByAuthMethod } from '../../utils/lit';
import { LitAbility, LitActionResource, LitPKPResource } from '@lit-protocol/auth-helpers';
import { IRelayPKP } from '@lit-protocol/types';
import useLocalStorage from '@rehooks/local-storage';
import { sessionSigsExpired } from '@/utils/app';
import {litNodeClientAtom} from '@/atoms/atoms'
import { useRecoilValue } from 'recoil';
export default function useLitSession() {
  const [sessionSigs, setSessionSigs] = useLocalStorage<SessionSigs>("sessionSigs");
  const [sessionLoading, setLoading] = useState<boolean>(false);
  const [sessionError, setError] = useState<Error>();
  const litNodeClient = useRecoilValue(litNodeClientAtom);

  const initSession = useCallback(
    async (authMethod: AuthMethod, currentAccount: IRelayPKP): Promise<void> => {
      setLoading(true);
      setError(undefined);
      await litNodeClient.connect();
      console.log("latest blockhash", await litNodeClient.getLatestBlockhash())

      try {
        const provider = getProviderByAuthMethod(authMethod);
        if (!provider) {
          throw new Error('No provider object');
        }
        // console.log(" init session vals", {authMethod: Boolean(authMethod), currentAccount: Boolean(currentAccount), sessionSigs: Boolean(sessionSigs), sessionsSigsExpired: sessionSigsExpired(sessionSigs)})

        // console.log("sessions Condidtion", Boolean(provider && currentAccount?.publicKey && authMethod && (!sessionSigs|| sessionSigsExpired(sessionSigs))))

        if (provider && currentAccount?.publicKey && authMethod && (!sessionSigs|| sessionSigsExpired(sessionSigs))) {
          const resourceAbilityRequests = [
            {
              resource: new LitPKPResource('*'),
              ability: LitAbility.PKPSigning,
            },
            {
              resource: new LitActionResource('*'),
              ability: LitAbility.LitActionExecution,
            },
          ];

          try {
            const sessionSigs: SessionSigs = await litNodeClient.getPkpSessionSigs({
              pkpPublicKey: currentAccount.publicKey,
              authMethods: [authMethod],
              resourceAbilityRequests: resourceAbilityRequests
            });
            if (sessionSigs) {
              console.log(`setting sessionSigs:`, sessionSigs);
              setSessionSigs(sessionSigs);
            } else {
              console.log("problem getting session sigs", sessionSigs)
            }
          } catch (error) {
            console.error("Error in litNodeClient.getPkpSessionSigs:", error);
            throw error;
          }
        }
      } catch (error) {
        console.error("initSession error:", error);
        setError(error as Error);
      } finally {
        setLoading(false);
      }
    },
    [setSessionSigs ]
  );

  return {
    sessionSigs,
    initSession,
    sessionLoading,
    sessionError,
  };
}

Error @  await litNodeClient.connect();
lit-core.js:617 Uncaught (in promise) TypeError: Cannot assign to read only property '_connectingPromise' of object '#<LitNodeClient>'
    at LitNodeClient.connect (lit-core.js:617:33)
    at async eval (useLitSession.tsx:20:7)
    
lit-core.js:630 Uncaught (in promise) 
TypeError: Cannot add property contractContext, object is not extensible
    at LitNodeClient._connect (lit-core.js:630:41)

﻿



```

@joshlong145
@Ansonhkg
@MaximusHaximus

**Comment by spacesailor24** [comment]
Hey @zach-is-my-name is possible for you to provide a reproducible example? I tried the following and didn't receive any error when calling `litNodeClient.connect()`

```ts
import { LitNodeClient } from "@lit-protocol/lit-node-client";

(async () => {
  let litNodeClient;

  try {
    litNodeClient = new LitNodeClient({
      litNetwork: "cayenne",
      alertWhenUnauthorized: false,
      checkNodeAttestation: false,
      debug: false,
    });
    await litNodeClient.connect();
  } catch (error) {
    console.error(error);
  } finally {
    litNodeClient.disconnect();
  }
})();
```

In the meantime, I'll ping the SDK team to see if they're aware of anything that might cause this

**Comment by zach-is-my-name** [comment]
Thanks for looking at this. Yes I'll try to provide a reproduction

**Comment by zach-is-my-name** [comment]
I failed to reproduce it after factoring out the Recoil library.  Must be related to Recoil's state management of the litNodeClient instance. Not a Lit bug. Closing
