### ISSUE TITLE
[DEVS] CORS error while using new Wrapped-keys feature ()

### ISSUE THREAD

**Issue by capitaharlock** [LIT-Protocol/Issues-and-Reports#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

6.0.5

### Lit Network

manzano

### Description of the bug/issue

I am trying to test **importPrivateKey** method:

`
 const wallet = ethers.Wallet.createRandom()
 const pkpAddress = await importPrivateKey({
          pkpSessionSigs: globalState.litActionSessionSigs,
          litNodeClient: globalState.litNodeClient,
          privateKey: wallet.privateKey,
          publicKey: wallet.publicKey,
          keyType: "K256",
 })`
 
 I have created a repo so you can see full code and run it to test. I have also tested the examples provided in lit documentation unsuccesfully. I will add logs in a comment in this issue thread too.

**Full github runable code:**
https://github.com/capitaharlock/lit-protocol-wrapped-keys

**Logs:**
<img width="669" alt="image" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/24976fdd-fd0f-496e-ad51-2fcb66379f7c">

<img width="911" alt="image" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/4170baa3-fc79-422b-954c-7a4b19f6a059">

<img width="903" alt="image" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/8f0bb787-667b-4ad7-ad3a-414adf328de9">

<img width="868" alt="image" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/93732312/a6e6edf5-f7a7-4077-9292-a1069c0814c7">

### Severity of the bug

needed to complete our implementation.

### Steps To Reproduce

download repo.
install dependencies.
run.

### Link to code

https://github.com/capitaharlock/lit-protocol-wrapped-keys

**Comment by capitaharlock** [comment]
I did download developer-guides-code and execute the first test:
I have used the key provided in other examples from Lit:
ETHEREUM_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

**LOG in CAYENNE:**
yarn test:import
yarn run v1.22.19
$ npx @dotenvx/dotenvx run -- mocha test/**/importKey.spec.ts
[dotenvx@0.44.6] injecting env (2) from .env


  Importing an Ethereum key using importPrivateKey
🔄 Connecting LitContracts client to network...
✅ Connected LitContracts client to network
🔄 Minting new PKP...
tokenIdFromEvent: 0x57a8057874cff69e1d8a17a008883efb1cea779f10097a4e982e1c53384b7904
pkp pub key:  0x04f87d3473cea48620039c0aa8a7159b046802e5f5f00616fd0c82c25c1fba6a9a878f4f8e0050bbdfe23b87f024ad71a4a6cbc64a8c71b689687eeb8a9b9149cd
public key from token id 0x04f87d3473cea48620039c0aa8a7159b046802e5f5f00616fd0c82c25c1fba6a9a878f4f8e0050bbdfe23b87f024ad71a4a6cbc64a8c71b689687eeb8a9b9149cd
✅ Minted new PKP with public key: 04f87d3473cea48620039c0aa8a7159b046802e5f5f00616fd0c82c25c1fba6a9a878f4f8e0050bbdfe23b87f024ad71a4a6cbc64a8c71b689687eeb8a9b9149cd and ETH address: 0xCB7E6CA7d256a5049D01c431c4C5c53aa13A85d3
🔄 Connecting to Lit network...
✅ Connected to Lit network
🔄 Getting PKP Session Sigs...
Storage key "lit-session-key" is missing. Not a problem. Contiune...
Storage key "lit-wallet-sig" is missing. Not a problem. Continue...
Unable to store walletSig in local storage. Not a problem. Continue...
✅ Got PKP Session Sigs
publicKey 0x811aaed5b7806fc6bdc600238eeb10b62224b62828699eeb104d6bb70d32607d
publicKey 0x04d681721d105ef7c196fa18bfdb24f5d406a013218c4c105accf7be7e3ee1555b7b761665048c2f35b537535ed1d6a3bb430f93fed8a3de38c54fe710d92ff1d3
🔄 Importing private key...
ReferenceError: crypto is not defined
    at hashAccessControlConditions (/Users/asimovia/prj/dexcelerate/developer-guides-code/wrapped-keys/nodejs/packages/access-control-conditions/src/lib/hashing.ts:181:3)
    at LitNodeClient.LitCore.getHashedAccessControlConditions (/Users/asimovia/prj/dexcelerate/developer-guides-code/wrapped-keys/nodejs/packages/core/src/lib/lit-core.ts:1064:59)
    at LitNodeClient.LitNodeClientNodeJs.encrypt (/Users/asimovia/prj/dexcelerate/developer-guides-code/wrapped-keys/nodejs/packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts:1431:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at importPrivateKey (/Users/asimovia/prj/dexcelerate/developer-guides-code/wrapped-keys/nodejs/packages/wrapped-keys/src/lib/api/import-private-key.ts:33:45)
    at importKey (/Users/asimovia/prj/dexcelerate/developer-guides-code/wrapped-keys/nodejs/src/importKey.ts:51:28)
    at Context.<anonymous> (/Users/asimovia/prj/dexcelerate/developer-guides-code/wrapped-keys/nodejs/test/importKey.spec.ts:27:40)
    1) should import an Ethereum key and attach it to a new PKP


  0 passing (16s)
  1 failing

  1) Importing an Ethereum key using importPrivateKey
       should import an Ethereum key and attach it to a new PKP:
     AssertionError: expected undefined to equal '0xCB7E6CA7d256a5049D01c431c4C5c53aa13…'
      at Context.<anonymous> (test/importKey.spec.ts:34:43)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)



Command exited with exit code 1: /Users/asimovia/prj/dexcelerate/developer-guides-code/wrapped-keys/nodejs/node_modules/.bin/mocha test/**/importKey.spec.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


**LOG Manzano**
yarn test:import
yarn run v1.22.19
$ npx @dotenvx/dotenvx run -- mocha test/**/importKey.spec.ts
[dotenvx@0.44.6] injecting env (2) from .env


  Importing an Ethereum key using importPrivateKey
🔄 Connecting LitContracts client to network...
✅ Connected LitContracts client to network
🔄 Minting new PKP...
tokenIdFromEvent: 0x45a02064a3710c723274cd968783e4351f4c28d9e4950399fa6bfdb00339cde4
pkp pub key:  0x047220d74baf48cdeabe2c6f4a6380df8ded5b68cc1bf56f804f41492cfce1eba070e243e07ff28635083d0854bd27ff2c0b8138f61fa53c8f1fadc299aacc9fd9
public key from token id 0x047220d74baf48cdeabe2c6f4a6380df8ded5b68cc1bf56f804f41492cfce1eba070e243e07ff28635083d0854bd27ff2c0b8138f61fa53c8f1fadc299aacc9fd9
✅ Minted new PKP with public key: 047220d74baf48cdeabe2c6f4a6380df8ded5b68cc1bf56f804f41492cfce1eba070e243e07ff28635083d0854bd27ff2c0b8138f61fa53c8f1fadc299aacc9fd9 and ETH address: 0x575815A7f49e90a09638BC32a191B63D83F55f38
🔄 Connecting to Lit network...
✅ Connected to Lit network
🔄 Getting PKP Session Sigs...
Storage key "lit-session-key" is missing. Not a problem. Contiune...
Storage key "lit-wallet-sig" is missing. Not a problem. Continue...
errConstructorFunc {
  message: 'An unexpected has occured.',
  errorCode: 'NodeContractResolverConversionFailed',
  errorKind: 'Unexpected',
  status: 500,
  details: [ 'Contract call reverted with data: 0x' ],
  requestId: '0ac208bc92352'
}
    1) should import an Ethereum key and attach it to a new PKP


  0 passing (16s)
  1 failing

  1) Importing an Ethereum key using importPrivateKey
       should import an Ethereum key and attach it to a new PKP:
     AssertionError: expected undefined to equal '0x575815A7f49e90a09638BC32a191B63D83F…'
      at Context.<anonymous> (test/importKey.spec.ts:34:43)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)



Command exited with exit code 1: /Users/asimovia/prj/dexcelerate/developer-guides-code/wrapped-keys/nodejs/node_modules/.bin/mocha test/**/importKey.spec.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
